### ISSUE TITLE
Time for code released and the mAP IoU threshold  in paper

### ISSUE THREAD

**Issue by zhengye1995** [whlin-pku/RoIMix#1]
Hi，thanks for your awesome work for underwater detection， I am very interesting in it. Do you have any plan to release the code for your paper? 
And can you tell me the IoU threshold for mAP used in your paper， I see that you get a very high mAP up to 73.49% in URPC dataset, but I only get about 50% mAP (0.05:0.95:0.05) on val dataset.

Hope for your reply!

**Comment by whlin-pku** [comment]
Thanks for your appreciation, threshold of the result is 0.5, not using coco metric. The code, Ah ..., if I come back school, I would release it as fast as possible. (ps: I left my laptop at the lab _(°:з」∠)_。


Furthermore, mmdetection is powerful, you can try it ~

Good luck !




2020-03-13 13:13:16zhengye <notifications@github.com>wrote:




Hi，thanks for your awesome work for underwater detection， I am very interesting in it. Do you have any plan to release the code for your paper?
And can you tell me the IoU threshold for mAP used in your paper， I see that you get a very high mAP up to 73.49% in URPC dataset, but I only get about 50% mAP (0.05:0.95:0.05) on val dataset.

Hope for your reply!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.






Sincerely

Wei-Hong Lin

----------------------------




Digital Media R&D Center

School of Electronic and Computer Engineering

Peking University Shenzhen Graduate School

Address: 201, Building B, Peking University, University Town, Xili, Nanshan District, Shenzhen, China, 518055

**Comment by zhengye1995** [comment]
Thank you, hope we can go back school soon.
